# Header
menu:
  home: /
  dropdown menu:
    google: //www.google.com/

extmenu:
  github: //github.com/wzktravel/
  hexo: //zespia.tw/hexo/
  theme:
    biture: //github.com/wzktravel/hexo-theme-biture
    landscape: //github.com/tommy351/hexo-theme-landscape
    light: //github.com/tommy351/hexo-theme-light

# Content
excerpt_link: Read More

fancybox: true

# Miscellaneous
# google_analytics:
# google_universal_analytics:
# rss:

# duoshuo
duoshuo_shortname: wzktravel


